### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by S1SYPHOS** [RobLoach/metalsmith-jstransformer#11]
Hey there,
quick question: could it be possible that `jstransformers` breaks images, so they can't be displayed anymore?

I told `metalsmith-jstransformer` this:
```
.use(jstransformer({
  layoutPattern: 'layouts/**',
  defaultLayout: 'layouts/post.swig'
}))
```
Pretty basic, everything is working fine, templating-wise - but images get beaten up?!
Help much appreciated, if you need more information, please ask.

Thank you very much & good day to you, Sir!

**Comment by RobLoach** [comment]
Breaks images?

I don't believe it will act on any images. What are your images named?

**Comment by S1SYPHOS** [comment]
If you don't mind, have a look [here](https://github.com/S1SYPHOS/stefanzweifel.io).
Last time I checked it garbled output of `.htaccess`, `sitemap.xml` and `humans.txt` too, but everything went back to normal when I excluded `jstransformer` from the build - leaving me with unprocessed files..

I just don't get `metalsmith` and `swig` to work :question:

**Comment by S1SYPHOS** [comment]
Deleted repo, problem didn't seem to be related to your plugin, although I was totally sure.
My apologies, Sir.

**Comment by RobLoach** [comment]
> problem didn't seem to be related to your plugin

What was the cause of the issue? I am curious.
