### ISSUE TITLE
Create next version with last modification and publish it to npm

### ISSUE THREAD

**Issue by ycherniavsky** [RobLoach/metalsmith-jstransformer#24]
Could you please create next version of metalsmith-jstransformer with last modification (#22, #21, #20) and publish this version to npm.

**Comment by ycherniavsky** [comment]
@klaftertief thank you for [0.10.1](https://github.com/RobLoach/metalsmith-jstransformer/tree/0.10.1) version!

**Comment by RobLoach** [comment]
Thanks for opening the issu!
